# Generated by Django 4.1.7 on 2023-03-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('optionsJSON', models.TextField()),
                ('baseJSON', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Panoplie',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.item')),
            ],
            bases=('editor.item',),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.item')),
            ],
            bases=('editor.item',),
        ),
    ]
